name: gitleaks

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O .gitleaks.toml https://raw.githubusercontent.com/ycjcl868/gitleaks/master/.gitleaks.toml
      - name: gitleaks-action
        uses: gitleaks/gitleaks-action@v1.6.0
